title: Suraj's blog
author: Suraj Subramanian
email: surajsubramanian2000@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Machine Learning Enthusiast
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Suraj Subramanian
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: This_IsSuraj
    github:  SurajSubramanian
    linkedIn: suraj-subramanian-577a2a142
#     rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
